# Generated by Django 3.2.9 on 2024-01-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=2, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
